
build: build-chrome build-firefox

build-one browser:
  #! /usr/bin/env -S bash -e

  root="$(git rev-parse --show-toplevel)"

  nix build --out-link "result-{{browser}}" "$root#extension-{{browser}}"

  rm -rf "dist-{{browser}}" "dist-{{browser}}.zip"
  cp -rL "result-{{browser}}/dist-{{browser}}" "./dist-{{browser}}"
  cp -L "result-{{browser}}/dist-{{browser}}.zip" "./dist-{{browser}}.zip"
  chmod -R u+w "dist-{{browser}}" "dist-{{browser}}.zip"

build-chrome: (build-one "chrome")

build-firefox: (build-one "firefox")

deploy-firefox: build-firefox
  #! /usr/bin/env -S bash -e

  set -a
  source .secrets-firefox.env
  set +a

  npx \
    --no \
    web-ext sign \
    --source-dir dist-firefox \
    --channel=listed \
    --amo-metadata=zz-firefox-amo-metadata.json \
    --api-key="$jwt_issuer" \
    --api-secret="$jwt_secret"
