// Code generated by tommy; DO NOT EDIT.

package config_toml

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type ConfigDocument struct {
	data     Config
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if tableNode := d.cstDoc.FindTable("default-browser"); tableNode != nil {
		d.consumed["default-browser"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "browser"); err == nil {
			if err := d.data.DefaultBrowser.Browser.UnmarshalText([]byte(v)); err != nil {
				return nil, fmt.Errorf("browser: %w", err)
			}
			d.consumed["default-browser.browser"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "id"); err == nil {
			d.data.DefaultBrowser.Id = v
			d.consumed["default-browser.id"] = true
		}
	}

	return d, nil
}

func (d *ConfigDocument) Data() *Config { return &d.data }

func (d *ConfigDocument) Encode() ([]byte, error) {
	{
		tableNode := d.cstDoc.EnsureTable("default-browser")
		{
			v, err := d.data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("browser: %w", err)
			}
			if err := d.cstDoc.SetInContainer(tableNode, "browser", string(v)); err != nil {
				return nil, err
			}
		}
		if d.data.DefaultBrowser.Id != "" {
			if err := d.cstDoc.SetInContainer(tableNode, "id", d.data.DefaultBrowser.Id); err != nil {
				return nil, err
			}
		} else {
			_ = d.cstDoc.DeleteFromContainer(tableNode, "id")
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *ConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeConfigInto(data *Config, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if tableNode := doc.FindTableInContainer(container, "default-browser"); tableNode != nil {
		consumed[keyPrefix+"default-browser"] = true
		if v, err := document.GetFromContainer[string](doc, tableNode, "browser"); err == nil {
			if err := data.DefaultBrowser.Browser.UnmarshalText([]byte(v)); err != nil {
				return fmt.Errorf("browser: %w", err)
			}
			consumed[keyPrefix+"default-browser.browser"] = true
		}
		if v, err := document.GetFromContainer[string](doc, tableNode, "id"); err == nil {
			data.DefaultBrowser.Id = v
			consumed[keyPrefix+"default-browser.id"] = true
		}
	}

	return nil
}

func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	{
		tableNode := doc.EnsureTableInContainer(container, "default-browser")
		{
			v, err := data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return fmt.Errorf("browser: %w", err)
			}
			if err := doc.SetInContainer(tableNode, "browser", string(v)); err != nil {
				return err
			}
		}
		if data.DefaultBrowser.Id != "" {
			if err := doc.SetInContainer(tableNode, "id", data.DefaultBrowser.Id); err != nil {
				return err
			}
		} else {
			_ = doc.DeleteFromContainer(tableNode, "id")
		}
	}

	return nil
}
