// Code generated by tommy; DO NOT EDIT.

package config_toml

import (
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ConfigDocument struct {
	data     Config
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeConfig(input []byte) (*ConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ConfigDocument{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "default-browser" {
			d.consumed["default-browser"] = true
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "browser":
					if v, ok := cst.ExtractString(_kv); ok {
						if err := d.data.DefaultBrowser.Browser.UnmarshalText([]byte(v)); err != nil {
							return nil, fmt.Errorf("browser: %w", err)
						}
						d.consumed["default-browser.browser"] = true
					}
				case "id":
					if v, ok := cst.ExtractString(_kv); ok {
						d.data.DefaultBrowser.Id = v
						d.consumed["default-browser.id"] = true
					}
				}
			}
			break
		}
	}
	return d, nil
}
func (d *ConfigDocument) Data() *Config {
	return &d.data
}
func (d *ConfigDocument) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "default-browser")
		{
			v, err := d.data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("browser: %w", err)
			}
			if err := cst.SetAny(tableNode, "browser", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.DefaultBrowser.Id != "" {
			if err := cst.SetAny(tableNode, "id", d.data.DefaultBrowser.Id); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "id")
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *ConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *ConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *ConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *ConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *ConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeConfigInto(data *Config, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _ch := range doc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"default-browser" {
			consumed[keyPrefix+"default-browser"] = true
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "browser":
					if v, ok := cst.ExtractString(_kv); ok {
						if err := data.DefaultBrowser.Browser.UnmarshalText([]byte(v)); err != nil {
							return fmt.Errorf("browser: %w", err)
						}
						consumed[keyPrefix+"default-browser.browser"] = true
					}
				case "id":
					if v, ok := cst.ExtractString(_kv); ok {
						data.DefaultBrowser.Id = v
						consumed[keyPrefix+"default-browser.id"] = true
					}
				}
			}
			break
		}
	}
	return nil
}
func EncodeConfigFrom(data *Config, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "default-browser")
		{
			v, err := data.DefaultBrowser.Browser.MarshalText()
			if err != nil {
				return fmt.Errorf("browser: %w", err)
			}
			if err := cst.SetAny(tableNode, "browser", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.DefaultBrowser.Id != "" {
			if err := cst.SetAny(tableNode, "id", data.DefaultBrowser.Id); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "id")
		}
	}
	return nil
}
