schema = 3

[mod]
  [mod.'code.linenisgreat.com/dodder/go']
    version = 'v0.0.0-20260306145455-1f6d8283bded'
    hash = 'sha256-mNFgK9nZvyp1XBTN9pEqU3DsHT97xy3Dr7cxB/USniA='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/jsonschema-go']
    version = 'v0.4.2'
    hash = 'sha256-kNExU/AI+CS27tQntXEpFqSio+HV2wzo2P458jqncOk='

  [mod.'github.com/modelcontextprotocol/go-sdk']
    version = 'v1.2.0'
    hash = 'sha256-eZJr7ru3v3l3t46EhLYW7TuGqWFnx172vJA0SIoaOWA='

  [mod.'github.com/yosida95/uritemplate/v3']
    version = 'v3.0.2'
    hash = 'sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM='

  [mod.'golang.org/x/oauth2']
    version = 'v0.35.0'
    hash = 'sha256-QeleoXu+9K3LJZiw6/iPR+EQzi/OLDBTFdrP2/d1XN8='

  [mod.'golang.org/x/sys']
    version = 'v0.41.0'
    hash = 'sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk='

  [mod.'golang.org/x/term']
    version = 'v0.40.0'
    hash = 'sha256-tu8USqDmcWfwery/+xti/BdUpNLbMNmZeghBNDsj1fQ='

  [mod.'golang.org/x/text']
    version = 'v0.34.0'
    hash = 'sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM='

  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='
